fix: metaTovalue get null value
electron/remote pull request #151
Opened 2023-04-20 02:38 UTC by Rabbitzzc

https://github.com/electron/remote/blob/main/src/renderer/remote.ts#L180
https://github.com/electron/remote/issues/79#issuecomment-921004401

2023-06-12 18:22 UTC, erickzhao approved these changes

2023-06-12 18:23 UTC, erickzhao requested changes

2023-06-12 18:23 UTC, erickzhao commented on src/renderer/remote.ts
> +  if(!meta) return {}
```suggestion
  if (!meta) return {}
```

CI doesn't catch lint issues it seems?

2023-08-10 10:04 UTC, codebytere approved these changes

2023-08-22 02:35 UTC, Rabbitzzc commented
please..

2023-08-22 02:37 UTC, BlackHole1 approved these changes

2023-08-22 02:37 UTC, BlackHole1 commented
ping @erickzhao

2023-08-30 17:47 UTC, erickzhao approved these changes

2023-08-30 17:51 UTC, merged